### ISSUE TITLE
Width of the card is not properly adjusted in mobile mode 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [A-Lehmann-Elektro-AG/solar-flow-grafana#12]
The width is not properly adjusted when i see this in the mobile mode 

![image](https://github.com/user-attachments/assets/afa52e6b-516c-492d-9414-d9a995b8bea5)

**Comment by d1msk1y** [comment]
This is not a part of our plugin. The website, you're referring to, is hosted by Grafana - the platform the plugin is developed on

Closing due to irrelevancy.
