### ISSUE TITLE
Want to create the dark mode for the website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [A-Lehmann-Elektro-AG/solar-flow-grafana#13]
I want to create the dark mode for the website 
It looks amazing in the dark mode 

![image](https://github.com/user-attachments/assets/7afb4023-2855-47df-86d4-009c2066d6af)

**Comment by d1msk1y** [comment]
This is not a part of our plugin. The website, you're referring to, is hosted by Grafana - the platform the plugin is developed on

Go to Grafana's repo for such issues: https://github.com/grafana

Closing due to irrelevancy.
