### ISSUE TITLE
Adding Battery Charge and Discharge State

### ISSUE THREAD

**Issue by matzexcom** [A-Lehmann-Elektro-AG/solar-flow-grafana#8]
Hello,
Thank you very much for this nice solar flow chart. I am enjoying it.

I have a question/feature request. Do you plan to add a battery to the flow chart?

For example:

```
solar    --------
                |
                |------- load -------- grid
                |
battery ---------
```

To see if the battery is in a charging or discharging state.

**Comment by d1msk1y** [comment]
Hi, in glad you're enjoying it:). No we were not planning to, but I think that's a great idea, and we'll definitely reconsider it. 
Thanks for the idea and the feedback!

**Comment by ammarib12** [comment]
Same question as above: Can I add an EV panel to the flow chart? If so, how can I add it?

**Comment by d1msk1y** [comment]
@matzexcom, @ammarib12. Good news, We're currently working on a new update! Soon you'll be able to add another energy source, whether it's a Battery or an EV Panel. Stay updated :)
