### ISSUE TITLE
ADD NEW ICON 

### ISSUE THREAD

**Issue by ammarib12** [A-Lehmann-Elektro-AG/solar-flow-grafana#9]
Can I add an EV panel to the flow chart? If so, how can I add it?

![image](https://github.com/user-attachments/assets/380a670f-28a0-41c5-94b3-2c19da19a88b)

**Comment by d1msk1y** [comment]
You can't add a separate icon for it, however you can merge it with other solar data. You have to simply adjust your Solar query to read both EV and any other PV data you want.

Also, we're currently working on a new battery feature, that will be available soon (I saw you mentioned it in another issue). So stay tuned :)
